### PR TITLE
#19: pattern of dots

### PR DESCRIPTION
**Pull request by drnikki**

### CODE REVIEW

**Comment by michaeljscrockett26** [comment]
Pattern should rotate every 3 rows (`; : .`) instead of every 2 rows (`; :`).

**Comment by drnikki** [comment]
@michaeljscrockett26 thank you for that good catch!!  I didn't even notice!

**Comment by michaeljscrockett26** [comment]
@drnikki The current pattern will print every even row as a `:` and every odd third row as `.` instead of cycling through the patterns. I believe the conditions for the if statements should instead be `x % 3 === 0` for `:` and ` x % 3 == 2` for `.`.

**Review by michaeljscrockett26 — CHANGES_REQUESTED** [review]
@drnikki The current pattern will print every even row as a `:` and every odd third row as `.` instead of cycling through the patterns. I believe the conditions for the if statements should instead be `x % 3 === 0` for `:` and  `x % 3 == 2` for `.`.

**Pull request merged**
